<a href="https://colab.research.google.com/github/Reuben17/Data_cleaning/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Obtaining the Dataset

In [ ]:
import pandas as pd
import io
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving modified_data.csv to modified_data (2).csv


In [ ]:
dataset = pd.read_csv(io.BytesIO(uploaded['modified_data.csv']))
print(dataset)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0            Lvl    AllPub    Inside  ... 

# Dataset Details and Dropping

In [ ]:
dataset.head(2)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   

  Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    AllPub    Inside  ...             0         0           0        0   
1    AllPub       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  

[2 rows x 77 columns]

In [ ]:
dataset.shape

(1460, 77)

In [ ]:
dataset.drop('Id',inplace = True,axis=1)

In [ ]:
dataset.head(2)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  

[2 rows x 76 columns]

In [ ]:
original_features=list(dataset.columns)
len(original_features)

76

It is zero as now everything has been filled

In [ ]:
features_missing_values=list(dataset.columns[dataset.isna().any()])
len(features_missing_values)

NameError: ignored

In [ ]:
len(dataset)

1460

# Filling Missing Features

In [ ]:
bfill,mean_fill=[],[]

In [ ]:
for feature in features_missing_values:
  print(feature,' ',dataset[feature].isna().sum()/len(dataset)*100,' ',dataset[feature].dtype)
  if dataset[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [ ]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [ ]:
for feature in mean_fill:
  dataset[feature].fillna(dataset[feature].mean(),inplace=True)

In [ ]:
bfill

['MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [ ]:
for feature in bfill:
  dataset[feature].fillna(method='bfill',inplace=True)

In [ ]:
dataset.columns[dataset.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [ ]:
dataset['FireplaceQu'].isna().sum()

2

In [ ]:
dataset['FireplaceQu'].fillna(method='ffill',inplace=True)

In [ ]:
dataset.head(1)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  

[1 rows x 76 columns]

# Encoding Dataset

In [ ]:
categorical_features=list(dataset.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
numerical_features=list(set(original_features)-set(categorical_features))
numerical_features

['GarageCars',
 '1stFlrSF',
 'WoodDeckSF',
 'OverallQual',
 'GarageArea',
 'FullBath',
 'PoolArea',
 'MiscVal',
 'SalePrice',
 '2ndFlrSF',
 'TotRmsAbvGrd',
 'HalfBath',
 'BsmtFullBath',
 'TotalBsmtSF',
 'BsmtHalfBath',
 'GarageYrBlt',
 'KitchenAbvGr',
 'BsmtFinSF2',
 'LotFrontage',
 '3SsnPorch',
 'BsmtUnfSF',
 'YearRemodAdd',
 'OpenPorchSF',
 'ScreenPorch',
 'LowQualFinSF',
 'MoSold',
 'BedroomAbvGr',
 'EnclosedPorch',
 'OverallCond',
 'GrLivArea',
 'LotArea',
 'YrSold',
 'Fireplaces',
 'BsmtFinSF1',
 'YearBuilt',
 'MasVnrArea',
 'MSSubClass']

In [ ]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [ ]:
target=['SalePrice']

In [ ]:
dataset_nominal=pd.get_dummies(dataset[nominal])

In [ ]:
for feature in ordinal:
  dataset[feature]=dataset[feature].astype('category').cat.codes

dataset_ordinal=dataset[ordinal]

In [ ]:
dataset[numerical_features]

GarageCars  1stFlrSF  WoodDeckSF  OverallQual  GarageArea  FullBath  \
0              2       856           0            7         548         2   
1              2      1262         298            6         460         2   
2              2       920           0            7         608         2   
3              3       961           0            7         642         1   
4              3      1145         192            8         836         2   
...          ...       ...         ...          ...         ...       ...   
1455           2       953           0            6         460         2   
1456           2      2073         349            6         500         2   
1457           1      1188           0            7         252         2   
1458           1      1078         366            5         240         1   
1459           1      1256         736            5         276         1   

      PoolArea  MiscVal  SalePrice  2ndFlrSF  ...  EnclosedPorch  OverallCond  \
0            0        0     208500       854  ...              0            5   
1            0        0     181500         0  ...              0            8   
2            0        0     223500       866  ...              0            5   
3            0        0     140000       756  ...            272            5   
4            0        0     250000      1053  ...              0            5   
...        ...      ...        ...       ...  ...            ...          ...   
1455         0        0     175000       694  ...              0            5   
1456         0        0     210000         0  ...              0            6   
1457         0     2500     266500      1152  ...              0            9   
1458         0        0     142125         0  ...            112            6   
1459         0        0     147500         0  ...              0            6   

      GrLivArea  LotArea  YrSold  Fireplaces  BsmtFinSF1  YearBuilt  \
0          1710     8450    2008           0         706       2003   
1          1262     9600    2007           1         978       1976   
2          1786    11250    2008           1         486       2001   
3          1717     9550    2006           1         216       1915   
4          2198    14260    2008           1         655       2000   
...         ...      ...     ...         ...         ...        ...   
1455       1647     7917    2007           1           0       1999   
1456       2073    13175    2010           2         790       1978   
1457       2340     9042    2010           2         275       1941   
1458       1078     9717    2010           0          49       1950   
1459       1256     9937    2008           0         830       1965   

      MasVnrArea  MSSubClass  
0          196.0          60  
1            0.0          20  
2          162.0          60  
3            0.0          70  
4          350.0          60  
...          ...         ...  
1455         0.0          60  
1456       119.0          20  
1457         0.0          70  
1458         0.0          20  
1459         0.0          20  

[1460 rows x 37 columns]

In [ ]:
new_dataset=pd.concat([dataset_nominal,dataset_ordinal,dataset[numerical_features]],axis=1)

In [ ]:
print(new_dataset.shape)

(1460, 107)


# Standardization 

In [ ]:
new_dataset.drop('SalePrice',axis=1,inplace=True)

In [ ]:
X=new_dataset.to_numpy()

In [ ]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888, -0.03174026,
       -0.40936914, -0.23012211,  0.28780036,  0.22403433,  0.31386709,
        0.60466978,  0.26381257,  0.25597761,  0.06423821, -0.02618016,
       -0.49151573,  0.2085023 , -0.41169079,  0.64046232,  0.30941909,
        1.11993319, -0.22571613, -0.71775144, -1.23804229,  0.75162623,
        0.83559903,  0.28974476, -0.29055229, -0.12304604,  0.303692  ,
        1.02668924,  0.75073056,  0.74309239,  0.18797343, -0.77797579,
       -0.03628912, -0.12579688, -0.40779461,  0.36420746, -0.88

In [ ]:
scale_X = StandardScaler()
X=scale_X.fit_transform(X)

In [ ]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888, -0.03174026,
       -0.40936914, -0.23012211,  0.28780036,  0.22403433,  0.31386709,
        0.60466978,  0.26381257,  0.25597761,  0.06423821, -0.02618016,
       -0.49151573,  0.2085023 , -0.41169079,  0.64046232,  0.30941909,
        1.11993319, -0.22571613, -0.71775144, -1.23804229,  0.75162623,
        0.83559903,  0.28974476, -0.29055229, -0.12304604,  0.303692  ,
        1.02668924,  0.75073056,  0.74309239,  0.18797343, -0.77797579,
       -0.03628912, -0.12579688, -0.40779461,  0.36420746, -0.88

In [ ]:
y=dataset[target]

In [ ]:
y=y.to_numpy()
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
y.shape

(1460, 1)

In [ ]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
scale_y = StandardScaler()
y=scale_y.fit_transform(y)

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [ ]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2, shuffle = False)

In [ ]:
X.shape

(1460, 106)

# Feature Extraction Using PCA

In [ ]:
pca=PCA(n_components=2)
pca_test=PCA(n_components=2)

In [ ]:
p_components=pca.fit_transform(X_train)
p_components_test=pca_test.fit_transform(X_test)

In [ ]:
p_components

array([[ 2.50218842, -1.0411232 ],
       [ 0.30530979,  2.79083483],
       [ 2.91452285, -0.57382158],
       ...,
       [ 3.50299244, -1.36609993],
       [ 3.86594925, -0.60123627],
       [ 2.25711887, -0.3837419 ]])

In [ ]:
pca.explained_variance_ratio_

array([0.10470377, 0.04484692])

In [ ]:
pca_data = pd.DataFrame(p_components,columns=['PC1','PC2'])
target_data = pd.DataFrame(y_train,columns=['SalePrice'])

pca_test_data = pd.DataFrame(p_components_test,columns=['PC1','PC2'])
target_test_data = pd.DataFrame(y_test,columns=['SalePrice'])

final_data = pd.concat([pca_data,target_data],axis=1)
final_data

PC1       PC2  SalePrice
0     2.502188 -1.041123   0.347273
1     0.305310  2.790835   0.007288
2     2.914523 -0.573822   0.536154
3    -1.345759  0.434489  -0.515281
4     5.169639 -0.259021   0.869843
...        ...       ...        ...
1163 -2.326350  1.634712  -0.906150
1164  1.134940  2.662856   0.164689
1165  3.502992 -1.366100   0.657919
1166  3.865949 -0.601236   0.811290
1167  2.257119 -0.383742  -0.099744

[1168 rows x 3 columns]

# Installing Tensorflow

In [ ]:
pip install --upgrade pip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install tf-nightly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# ANN Model

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, input_shape=(2,), activation='tanh'),
    tf.keras.layers.Dense(4, activation = 'tanh'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam',loss = 'mean_squared_error')

model.fit(pca_data, target_data, epochs=1000, batch_size=2)


Epoch 1/1000
584/584 [==============================] - 2s 2ms/step - loss: 0.5132
Epoch 2/1000
584/584 [==============================] - 1s 1ms/step - loss: 0.3892
Epoch 3/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.3063
Epoch 4/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2698
Epoch 5/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2500
Epoch 6/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2367
Epoch 7/1000
584/584 [==============================] - 1s 1ms/step - loss: 0.2263
Epoch 8/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2165
Epoch 9/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2106
Epoch 10/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.2060
Epoch 11/1000
584/584 [==============================] - 1s 1ms/step - loss: 0.2024
Epoch 12/1000
584/584 [==============================] - 1s 2ms/step - loss: 0.1991
E

In [ ]:
loss = model.evaluate(pca_test_data, target_test_data,batch_size = 2)
print(loss)

146/146 [==============================] - 0s 1ms/step - loss: 0.2592
0.2592238485813141


In [ ]:
predictions =model.predict(pca_test_data)
predictions = scale_y.inverse_transform(predictions)
features = pca_test_data
output_y = pd.DataFrame(predictions,columns=['Predictions'])
output = pd.concat([features,output_y],axis=1)

output



10/10 [==============================] - 0s 2ms/step


PC1       PC2    Predictions
0    0.210558  2.372315  170377.000000
1    9.411013  3.479734  556711.250000
2    1.568859  4.877584  224172.656250
3   -0.942123  0.724642  154108.578125
4    0.569310 -4.985899  172288.734375
..        ...       ...            ...
287  0.814534 -1.770234  174608.625000
288  1.357379  1.765891  193710.265625
289  1.185217  1.748692  189619.578125
290 -2.762836 -0.017426  131043.453125
291 -0.672296  0.262278  159231.312500

[292 rows x 3 columns]